# Generated by Django 6.0.1 on 2026-01-27 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformer_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity_kva', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheftPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('loss_ratio', models.FloatField()),
                ('theft_probability', models.FloatField()),
                ('theft_detected', models.BooleanField()),
                ('model_version', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.transformer')),
            ],
        ),
        migrations.CreateModel(
            name='CashPowerMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=50, unique=True)),
                ('installation_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='monitoring.transformer')),
            ],
        ),
        migrations.CreateModel(
            name='TransformerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('energy_supplied_kwh', models.FloatField()),
                ('total_meter_consumption_kwh', models.FloatField()),
                ('loss_kwh', models.FloatField()),
                ('loss_ratio', models.FloatField()),
                ('theft_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.transformer')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='monitoring__timesta_83e24c_idx'), models.Index(fields=['transformer'], name='monitoring__transfo_e5b661_idx'), models.Index(fields=['theft_flag'], name='monitoring__theft_f_885aa7_idx')],
            },
        ),
    ]
